package cheanxin.enums;

/**
 * Created by Jawinton on 17/01/03.
 */
public enum Authority {
    // 贷款初审相关权限
    ROLE_FIRST_REVIEW_PENDING_TO_FIRST_REVIEW_PENDING,
    ROLE_FIRST_REVIEW_PENDING_TO_FIRST_REVIEW_ACCEPTED,
    ROLE_FIRST_REVIEW_PENDING_TO_FIRST_REVIEW_REJECTED,

    // 贷款草稿相关权限
    ROLE_FIRST_DRAFT_TO_FIRST_DRAFT,
    ROLE_FIRST_DRAFT_TO_SECOND_DRAFT,
    ROLE_SECOND_DRAFT_TO_SECOND_DRAFT,
    ROLE_SECOND_DRAFT_TO_LOAN,

    // 产品相关权限
    ROLE_PENDING_REVIEW_TO_ACCEPTED,
    ROLE_PENDING_REVIEW_TO_REJECTED;
}
